export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS ="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL ="USER_REGISTER_FAIL"

export const USER_FORGOTPASS_REQUEST ="USER_FORGOTPASS_REQUEST"
export const USER_FORGOTPASS_SUCCESS ="USER_FORGOTPASS_SUCCESS"
export const USER_FORGOTPASS_FAIL ="USER_FORGOTPASS_FAIL"