export const FETCH_SEED_REQUEST = 'FETCH_SEED_REQUEST';
export const FETCH_SEED_SUCCESS = 'FETCH_SEED_SUCCESS';
export const FETCH_SEED_FAIL = 'FETCH_SEED_FAIL';

export const CREATE_SEED_REQUEST = 'CREATE_SEED_REQUEST';
export const CREATE_SEED_SUCCESS = 'CREATE_SEED_SUCCESS';
export const CREATE_SEED_FAIL = 'CREATE_SEED_FAIL';
export const CREATE_SEED_RESET = 'CREATE_SEED_RESET';

export const UPDATE_SEED_REQUEST = 'UPDATE_SEED_REQUEST';
export const UPDATE_SEED_SUCCESS = 'UPDATE_SEED_SUCCESS';
export const UPDATE_SEED_FAIL = 'UPDATE_SEED_FAIL';
export const UPDATE_SEED_RESET = 'UPDATE_SEED_RESET';

export const DELETE_SEED_REQUEST = 'DELETE_SEED_REQUEST';
export const DELETE_SEED_SUCCESS = 'DELETE_SEED_SUCCESS';
export const DELETE_SEED_FAIL = 'DELETE_SEED_FAIL';