export const FETCH_VENTEITEMS_REQUEST = 'FETCH_VENTEITEMS_REQUEST';
export const FETCH_VENTEITEMS_SUCCESS = 'FETCH_VENTEITEMS_SUCCESS';
export const FETCH_VENTEITEMS_FAIL = 'FETCH_VENTEITEMS_FAIL';

export const CREATE_VENTEITEMS_REQUEST = 'CREATE_VENTEITEMS_REQUEST';
export const CREATE_VENTEITEMS_SUCCESS = 'CREATE_VENTEITEMS_SUCCESS';
export const CREATE_VENTEITEMS_FAIL = 'CREATE_VENTEITEMS_FAIL';
export const CREATE_VENTEITEMS_RESET = 'CREATE_VENTEITEMS_RESET';

export const UPDATE_VENTEITEMS_REQUEST = 'UPDATE_VENTEITEMS_REQUEST';
export const UPDATE_VENTEITEMS_SUCCESS = 'UPDATE_VENTEITEMS_SUCCESS';
export const UPDATE_VENTEITEMS_FAIL = 'UPDATE_VENTEITEMS_FAIL';
export const UPDATE_VENTEITEMS_RESET = 'UPDATE_VENTEITEMS_RESET';

export const DELETE_VENTEITEMS_REQUEST = 'DELETE_VENTEITEMS_REQUEST';
export const DELETE_VENTEITEMS_SUCCESS = 'DELETE_VENTEITEMS_SUCCESS';
export const DELETE_VENTEITEMS_FAIL = 'DELETE_VENTEITEMS_FAIL';

export const DETAIL_VENTEITEMS_REQUEST = 'DETAIL_VENTEITEMS_REQUEST';
export const DETAIL_VENTEITEMS_SUCCESS = 'DETAIL_VENTEITEMS_SUCCESS';
export const DETAIL_VENTEITEMS_FAIL = 'DETAIL_VENTEITEMS_FAIL';